# Generated by Django 5.0.6 on 2024-06-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='image',
            field=models.ImageField(default='test', upload_to='building_images/'),
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default='test', upload_to='room_images/'),
        ),
    ]
