# Generated by Django 5.0.6 on 2024-06-05 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_building_description_room_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'Здание', 'verbose_name_plural': 'Здания'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Помещение', 'verbose_name_plural': 'Помещения'},
        ),
        migrations.AlterModelOptions(
            name='roomuser',
            options={'verbose_name': 'Пользователь помещения', 'verbose_name_plural': 'Пользователи помещений'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'verbose_name': 'Временной интервал', 'verbose_name_plural': 'Временные интервалы'},
        ),
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='building',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='building',
            name='image',
            field=models.ImageField(default='test', upload_to='building_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.building', verbose_name='Здание'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='room',
            name='free_places_counter',
            field=models.BigIntegerField(verbose_name='Количество свободных мест'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(default='test', upload_to='room_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='roomuser',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.building', verbose_name='Здание'),
        ),
        migrations.AlterField(
            model_name='roomuser',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.timeslot', verbose_name='Временной интервал'),
        ),
        migrations.AlterField(
            model_name='roomuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='current_bookings',
            field=models.IntegerField(default=0, verbose_name='Текущее количество бронирований'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.DateTimeField(verbose_name='Конечное время'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='max_bookings',
            field=models.IntegerField(verbose_name='Максимальное количество бронирований'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.room', verbose_name='Помещение'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.DateTimeField(verbose_name='Начальное время'),
        ),
    ]
