# Generated by Django 5.0.6 on 2024-06-05 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
